source 'https://github.com/CocoaPods/Specs'
platform :ios, "6.0"
inhibit_all_warnings!

pod 'Masonry', '~> 0.5.3'
pod 'MagicalRecord', '~> 2.2'
pod 'AFNetworking', '~> 2.4.1'
pod 'JSONModel', '~> 1.0.1'
pod 'JGProgressHUD', '~> 1.2.1'
pod 'SDWebImage', '~> 3.7.1'
pod 'IQKeyboardManager', '~> 3.2.0.1'

